// ── Domain Models ──────────────────────────────────────────────────────────────

export type ActionType =
  | 'click'
  | 'right_click'
  | 'double_click'
  | 'type'
  | 'key'
  | 'scroll'
  | 'navigate'
  | 'custom'

export type AiStatus = 'pending' | 'processing' | 'done' | 'error' | 'skipped'
export type ProjectStatus = 'draft' | 'complete' | 'archived'

export interface Project {
  id: string
  title: string
  description: string
  createdAt: number
  updatedAt: number
  thumbnailPath: string | null
  stepCount: number
  status: ProjectStatus
}

export interface Step {
  id: string
  projectId: string
  orderIndex: number
  actionType: ActionType
  x: number | null
  y: number | null
  scrollDeltaX: number | null
  scrollDeltaY: number | null
  typedText: string | null
  keyName: string | null
  appName: string | null
  windowTitle: string | null
  url: string | null
  screenshotPath: string | null
  screenshotWidth: number | null
  screenshotHeight: number | null
  fullScreenshotPath: string | null
  cropX: number | null
  cropY: number | null
  cropRadius: number | null
  scaleFactor: number | null
  description: string
  aiStatus: AiStatus
  aiError: string | null
  annotations: Annotation[]
  capturedAt: number
  createdAt: number
  updatedAt: number
}

export type Annotation =
  | { id: string; type: 'arrow'; x1: number; y1: number; x2: number; y2: number; color: string }
  | {
      id: string
      type: 'highlight'
      x: number
      y: number
      width: number
      height: number
      color: string
      opacity: number
    }
  | { id: string; type: 'redact'; x: number; y: number; width: number; height: number }
  | { id: string; type: 'text'; x: number; y: number; content: string; fontSize: number; color: string }
  | { id: string; type: 'click_dot'; x: number; y: number; color: string; opacity?: number }
  | {
      id: string
      type: 'draw'
      points: Array<[number, number]>
      color: string
      opacity: number
      strokeWidth: number
    }

// ── Settings ───────────────────────────────────────────────────────────────────

export interface AppSettings {
  anthropicApiKey: string
  defaultCropRadius: number
  defaultScreenshotDelay: number
  captureTyping: boolean
  captureScrolling: boolean
  autoGenerateDescriptions: boolean
  aiModel: string
  theme: 'light' | 'dark' | 'system'
}

// ── IPC Payloads ───────────────────────────────────────────────────────────────

export interface StartRecordingPayload {
  projectId: string
  displayId?: string
  captureMouseClicks: boolean
  captureTyping: boolean
  captureScrolling: boolean
  screenshotDelay: number
  cropRadius: number
}

export type RecordingState = 'idle' | 'recording' | 'paused' | 'stopping'

export interface RecordingStateChangedPayload {
  state: RecordingState
  projectId: string | null
  stepCount: number
  elapsedMs: number
}

export interface StepCapturedPayload {
  step: Step
}

export interface ProjectsListPayload {
  search?: string
  orderBy?: 'createdAt' | 'updatedAt' | 'title'
  orderDir?: 'asc' | 'desc'
}

export interface StepsReorderPayload {
  projectId: string
  orderedIds: string[]
}

export interface AiProgressPayload {
  projectId: string
  total: number
  completed: number
  currentStepId: string | null
}

export interface AiStepDonePayload {
  stepId: string
  description: string
  aiStatus: AiStatus
}

export interface ExportOptions {
  includeStepNumbers: boolean
  screenshotMaxWidth: number
}

export interface ExportPayload {
  projectId: string
  outputPath: string
  options: ExportOptions
}

export interface DisplayInfo {
  id: string
  label: string
  bounds: { x: number; y: number; width: number; height: number }
  isPrimary: boolean
}

export interface UpdateCropPayload {
  stepId: string
  cropX: number
  cropY: number
  cropRadius: number
}

// ── IPC Response wrapper ───────────────────────────────────────────────────────

export type IpcResult<T> = { data: T; error?: never } | { data?: never; error: string }
