import { create } from 'zustand'
import { settingsApi } from '../lib/ipc'
import type { AppSettings } from '../../../shared/types'
import {
  DEFAULT_CROP_RADIUS,
  DEFAULT_SCREENSHOT_DELAY_MS,
  DEFAULT_AI_PROVIDER,
  DEFAULT_AI_MODEL
} from '../../../shared/constants'

const DEFAULTS: AppSettings = {
  aiProvider: DEFAULT_AI_PROVIDER,
  aiApiKey: '',
  aiBaseUrl: '',
  aiModel: DEFAULT_AI_MODEL,
  defaultCropRadius: DEFAULT_CROP_RADIUS,
  defaultScreenshotDelay: DEFAULT_SCREENSHOT_DELAY_MS,
  captureTyping: true,
  captureScrolling: true,
  autoGenerateDescriptions: true,
  theme: 'system'
}

interface SettingsStore {
  settings: AppSettings
  isLoaded: boolean
  loadSettings: () => Promise<void>
  updateSettings: (patch: Partial<AppSettings>) => Promise<void>
}

export const useSettingsStore = create<SettingsStore>((set, get) => ({
  settings: DEFAULTS,
  isLoaded: false,

  loadSettings: async () => {
    const res = await settingsApi.get()
    if (res.data) set({ settings: res.data, isLoaded: true })
  },

  updateSettings: async (patch) => {
    const merged = { ...get().settings, ...patch }
    set({ settings: merged })
    await settingsApi.set(patch)
  }
}))
