import { IPC } from '@shared/ipcChannels'
import { recordingSession } from '../recordingSession'
import { batchProcessor } from '../ai/batchProcessor'
import { projectsRepo } from '../database/projectsRepo'
import { settingsRepo } from '../database/settingsRepo'
import { getDisplayList } from '../screenshotCapture'
import { showOverlay, hideOverlay, hideMain, showMain, sendToMain } from '../windowManager'
import { logger } from '../utils/logger'
import { validatedHandle } from '../security/ipcValidation'

export function registerRecordingHandlers(): void {
  // Relay session events to renderer (these are main->renderer, no validation needed).
  recordingSession.on('stateChanged', (payload) => sendToMain(IPC.RECORDING_STATE_CHANGED, payload))
  recordingSession.on('stepCaptured', (step) => sendToMain(IPC.RECORDING_STEP_CAPTURED, { step }))
  recordingSession.on('error', (err) => sendToMain(IPC.RECORDING_ERROR, { message: String(err) }))

  validatedHandle(IPC.RECORDING_START, 'recordingStart', async (_event, payload) => {
    try {
      await recordingSession.start(payload)
      hideMain()
      showOverlay()
      return { data: { success: true } }
    } catch (err) {
      logger.error('Start recording error:', err)
      return { error: String(err) }
    }
  })

  validatedHandle(IPC.RECORDING_STOP, 'recordingStop', async () => {
    try {
      const projectId = await recordingSession.stop()
      hideOverlay()
      showMain()

      // Auto-trigger AI if enabled and key is set
      if (projectId) {
        const settings = await settingsRepo.get()
        if (settings.autoGenerateDescriptions && settings.anthropicApiKey) {
          const project = projectsRepo.get(projectId)
          if (project) {
            batchProcessor.processProject(projectId, project.title).catch((e) => logger.error('AI batch error:', e))
          }
        }
      }

      return { data: { projectId } }
    } catch (err) {
      return { error: String(err) }
    }
  })

  validatedHandle(IPC.RECORDING_PAUSE, 'recordingPause', () => {
    recordingSession.pause()
    return { data: { success: true } }
  })

  validatedHandle(IPC.RECORDING_RESUME, 'recordingResume', () => {
    recordingSession.resume()
    return { data: { success: true } }
  })

  validatedHandle(IPC.GET_DISPLAYS, 'getDisplays', async () => {
    try {
      const displays = await getDisplayList()
      return { data: displays }
    } catch (err) {
      return { error: String(err) }
    }
  })
}
