import { ipcMain } from 'electron'
import { IPC } from '@shared/ipcChannels'
import { recordingSession } from '../recordingSession'
import { batchProcessor } from '../ai/batchProcessor'
import { projectsRepo } from '../database/projectsRepo'
import { settingsRepo } from '../database/settingsRepo'
import { getDisplayList } from '../screenshotCapture'
import {
  showOverlay,
  hideOverlay,
  hideMain,
  showMain,
  sendToMain,
  sendToOverlay,
  minimizeOverlay
} from '../windowManager'
import { logger } from '../utils/logger'
import { validatedHandle } from '../security/ipcValidation'

export function registerRecordingHandlers(): void {
  // Relay session events to BOTH the main window (for the dashboard step list)
  // AND the floating overlay (for the live timer + step counter).
  recordingSession.on('stateChanged', (payload) => {
    sendToMain(IPC.RECORDING_STATE_CHANGED, payload)
    sendToOverlay(IPC.RECORDING_STATE_CHANGED, payload)
  })
  recordingSession.on('stepCaptured', (step) => {
    sendToMain(IPC.RECORDING_STEP_CAPTURED, { step })
    sendToOverlay(IPC.RECORDING_STEP_CAPTURED, { step })
  })
  // 1Hz tick — drives the overlay's stopwatch when no other event is firing.
  recordingSession.on('tick', (payload) => {
    sendToMain(IPC.RECORDING_TICK, payload)
    sendToOverlay(IPC.RECORDING_TICK, payload)
  })
  recordingSession.on('error', (err) => sendToMain(IPC.RECORDING_ERROR, { message: String(err) }))

  // Minimize button on the overlay window. No payload validation needed —
  // the channel takes no arguments and only affects window state.
  ipcMain.handle(IPC.RECORDING_MINIMIZE_OVERLAY, () => {
    minimizeOverlay()
    return { data: { success: true } }
  })

  validatedHandle(IPC.RECORDING_START, 'recordingStart', async (_event, payload) => {
    try {
      await recordingSession.start(payload)
      hideMain()
      showOverlay()
      return { data: { success: true } }
    } catch (err) {
      logger.error('Start recording error:', err)
      return { error: String(err) }
    }
  })

  validatedHandle(IPC.RECORDING_STOP, 'recordingStop', async () => {
    try {
      const projectId = await recordingSession.stop()
      hideOverlay()
      showMain()

      // Auto-trigger AI if enabled and credentials are configured
      if (projectId) {
        const settings = await settingsRepo.get()
        // openai-compatible providers (Ollama / LM Studio / vLLM) accept
        // unauthenticated requests, so an empty key is fine for that mode.
        const credsOk = settings.aiProvider === 'openai-compatible' || !!settings.aiApiKey
        if (settings.autoGenerateDescriptions && credsOk) {
          const project = projectsRepo.get(projectId)
          if (project) {
            batchProcessor.processProject(projectId, project.title).catch((e) => logger.error('AI batch error:', e))
          }
        }
      }

      return { data: { projectId } }
    } catch (err) {
      return { error: String(err) }
    }
  })

  validatedHandle(IPC.RECORDING_PAUSE, 'recordingPause', () => {
    recordingSession.pause()
    return { data: { success: true } }
  })

  validatedHandle(IPC.RECORDING_RESUME, 'recordingResume', () => {
    recordingSession.resume()
    return { data: { success: true } }
  })

  validatedHandle(IPC.GET_DISPLAYS, 'getDisplays', async () => {
    try {
      const displays = await getDisplayList()
      return { data: displays }
    } catch (err) {
      return { error: String(err) }
    }
  })
}
