import { getDb } from './connection'
import type { AppSettings } from '@shared/types'
import { DEFAULT_CROP_RADIUS, DEFAULT_SCREENSHOT_DELAY_MS, DEFAULT_AI_MODEL } from '@shared/constants'

const DEFAULTS: AppSettings = {
  anthropicApiKey: '',
  defaultCropRadius: DEFAULT_CROP_RADIUS,
  defaultScreenshotDelay: DEFAULT_SCREENSHOT_DELAY_MS,
  captureTyping: true,
  captureScrolling: true,
  autoGenerateDescriptions: true,
  aiModel: DEFAULT_AI_MODEL,
  theme: 'system'
}

export const settingsRepo = {
  get(): AppSettings {
    const db = getDb()
    const rows = db.prepare('SELECT key, value FROM settings').all() as { key: string; value: string }[]
    const map: Record<string, string> = {}
    rows.forEach((r) => { map[r.key] = r.value })

    return {
      anthropicApiKey: map['anthropicApiKey'] ?? DEFAULTS.anthropicApiKey,
      defaultCropRadius: map['defaultCropRadius'] ? Number(map['defaultCropRadius']) : DEFAULTS.defaultCropRadius,
      defaultScreenshotDelay: map['defaultScreenshotDelay'] ? Number(map['defaultScreenshotDelay']) : DEFAULTS.defaultScreenshotDelay,
      captureTyping: map['captureTyping'] !== undefined ? map['captureTyping'] === 'true' : DEFAULTS.captureTyping,
      captureScrolling: map['captureScrolling'] !== undefined ? map['captureScrolling'] === 'true' : DEFAULTS.captureScrolling,
      autoGenerateDescriptions: map['autoGenerateDescriptions'] !== undefined ? map['autoGenerateDescriptions'] === 'true' : DEFAULTS.autoGenerateDescriptions,
      aiModel: map['aiModel'] ?? DEFAULTS.aiModel,
      theme: (map['theme'] as AppSettings['theme']) ?? DEFAULTS.theme
    }
  },

  set(patch: Partial<AppSettings>): void {
    const db = getDb()
    const upsert = db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)')
    const tx = db.transaction(() => {
      Object.entries(patch).forEach(([k, v]) => upsert.run(k, String(v)))
    })
    tx()
  },

  getKey(key: keyof AppSettings): string | null {
    const row = getDb().prepare('SELECT value FROM settings WHERE key = ?').get(key) as { value: string } | undefined
    return row?.value ?? null
  }
}
