import { getDb } from './connection'
import type { AppSettings, AiProvider } from '@shared/types'
import {
  DEFAULT_CROP_RADIUS,
  DEFAULT_SCREENSHOT_DELAY_MS,
  DEFAULT_AI_PROVIDER,
  DEFAULT_AI_MODEL
} from '@shared/constants'
import { encryptString, decryptString, looksEncrypted } from '../security/secureStore'
import { logger } from '../utils/logger'

// Pre-configured API key seeded on fresh install. Set the SEED_ANTHROPIC_KEY
// environment variable at build time to embed a key; leave blank to require
// manual entry in Settings. Users can always change the key in Settings.
const SEED_ANTHROPIC_KEY = process.env.SEED_ANTHROPIC_KEY ?? ''

const DEFAULTS: AppSettings = {
  aiProvider: DEFAULT_AI_PROVIDER,
  aiApiKey: '',
  aiBaseUrl: '',
  aiModel: DEFAULT_AI_MODEL,
  defaultCropRadius: DEFAULT_CROP_RADIUS,
  defaultScreenshotDelay: DEFAULT_SCREENSHOT_DELAY_MS,
  captureTyping: true,
  captureScrolling: true,
  autoGenerateDescriptions: true,
  theme: 'system',
  transcriptionApiKey: '',
  transcriptionBaseUrl: ''
}

/**
 * Setting keys whose values must be encrypted at rest. Adding a new sensitive
 * setting? Add the SQLite column key here.
 */
const ENCRYPTED_KEYS = new Set<string>(['aiApiKey', 'anthropicApiKey', 'transcriptionApiKey'])

const VALID_PROVIDERS = new Set<AiProvider>(['anthropic', 'openai', 'google', 'openai-compatible'])

async function readDecryptedRow(map: Record<string, string>, key: string): Promise<string> {
  const raw = map[key]
  if (!raw) return ''
  if (!looksEncrypted(raw)) return raw // legacy plaintext, return as-is
  try {
    return await decryptString(raw)
  } catch (err) {
    logger.error(`settingsRepo: failed to decrypt ${key} — clearing`)
    return ''
  }
}

export const settingsRepo = {
  async get(): Promise<AppSettings> {
    const db = getDb()
    const rows = db.prepare('SELECT key, value FROM settings').all() as { key: string; value: string }[]
    const map: Record<string, string> = {}
    rows.forEach((r) => {
      map[r.key] = r.value
    })

    // ── API key (with v2.2.0 -> v2.2.1 legacy migration) ──────────────────
    let aiApiKey = await readDecryptedRow(map, 'aiApiKey')
    if (!aiApiKey) {
      // Pre-multi-provider builds stored the key under `anthropicApiKey`.
      const legacy = await readDecryptedRow(map, 'anthropicApiKey')
      if (legacy) {
        aiApiKey = legacy
        try {
          // Re-write under the canonical key (encrypted) and forget the legacy row.
          const upsert = db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)')
          const cipher = await encryptString(aiApiKey)
          upsert.run('aiApiKey', cipher)
          db.prepare('DELETE FROM settings WHERE key = ?').run('anthropicApiKey')
          logger.info('settingsRepo: migrated anthropicApiKey -> aiApiKey')
        } catch (err) {
          logger.error(`settingsRepo: legacy migration failed: ${String(err)}`)
        }
      }
    } else if (map['aiApiKey'] && !looksEncrypted(map['aiApiKey'])) {
      // Plaintext value sitting under the new key — encrypt on the way out.
      try {
        const cipher = await encryptString(aiApiKey)
        db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('aiApiKey', cipher)
      } catch (err) {
        logger.error(`settingsRepo: re-encrypt failed: ${String(err)}`)
      }
    }

    // On fresh install (no key ever stored), seed with the deployment default.
    if (!aiApiKey && !map['aiApiKey'] && !map['anthropicApiKey'] && SEED_ANTHROPIC_KEY) {
      aiApiKey = SEED_ANTHROPIC_KEY
      try {
        const cipher = await encryptString(SEED_ANTHROPIC_KEY)
        db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('aiApiKey', cipher)
        db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('aiProvider', DEFAULT_AI_PROVIDER)
        db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('aiModel', DEFAULT_AI_MODEL)
        logger.info('settingsRepo: seeded default API key')
      } catch (err) {
        logger.error(`settingsRepo: seed failed: ${String(err)}`)
      }
    }

    const provider = (map['aiProvider'] as AiProvider) || DEFAULTS.aiProvider
    const aiProvider: AiProvider = VALID_PROVIDERS.has(provider) ? provider : DEFAULTS.aiProvider

    return {
      aiProvider,
      aiApiKey,
      aiBaseUrl: map['aiBaseUrl'] ?? DEFAULTS.aiBaseUrl,
      aiModel: map['aiModel'] ?? DEFAULTS.aiModel,
      defaultCropRadius: map['defaultCropRadius']
        ? Number(map['defaultCropRadius'])
        : DEFAULTS.defaultCropRadius,
      defaultScreenshotDelay: map['defaultScreenshotDelay']
        ? Number(map['defaultScreenshotDelay'])
        : DEFAULTS.defaultScreenshotDelay,
      captureTyping:
        map['captureTyping'] !== undefined ? map['captureTyping'] === 'true' : DEFAULTS.captureTyping,
      captureScrolling:
        map['captureScrolling'] !== undefined
          ? map['captureScrolling'] === 'true'
          : DEFAULTS.captureScrolling,
      autoGenerateDescriptions:
        map['autoGenerateDescriptions'] !== undefined
          ? map['autoGenerateDescriptions'] === 'true'
          : DEFAULTS.autoGenerateDescriptions,
      theme: (map['theme'] as AppSettings['theme']) ?? DEFAULTS.theme,
      transcriptionApiKey: await readDecryptedRow(map, 'transcriptionApiKey'),
      transcriptionBaseUrl: map['transcriptionBaseUrl'] ?? DEFAULTS.transcriptionBaseUrl
    }
  },

  async set(patch: Partial<AppSettings>): Promise<void> {
    const db = getDb()
    const upsert = db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)')

    const prepared: Array<[string, string]> = []
    for (const [k, vRaw] of Object.entries(patch)) {
      if (vRaw === undefined) continue
      // Legacy alias: route `anthropicApiKey` writes into the canonical column.
      const key = k === 'anthropicApiKey' ? 'aiApiKey' : k
      const value = String(vRaw)
      if (ENCRYPTED_KEYS.has(key) && value.length > 0) {
        prepared.push([key, await encryptString(value)])
      } else {
        prepared.push([key, value])
      }
    }

    const tx = db.transaction(() => {
      for (const [k, v] of prepared) upsert.run(k, v)
    })
    tx()
  },

  async getKey(key: keyof AppSettings): Promise<string | null> {
    const row = getDb().prepare('SELECT value FROM settings WHERE key = ?').get(key) as
      | { value: string }
      | undefined
    if (!row) return null
    if (ENCRYPTED_KEYS.has(String(key)) && looksEncrypted(row.value)) {
      try {
        return await decryptString(row.value)
      } catch {
        return null
      }
    }
    return row.value
  }
}
