import { getDb } from './connection'
import type { AppSettings } from '@shared/types'
import { DEFAULT_CROP_RADIUS, DEFAULT_SCREENSHOT_DELAY_MS, DEFAULT_AI_MODEL } from '@shared/constants'
import { encryptString, decryptString, looksEncrypted } from '../security/secureStore'
import { logger } from '../utils/logger'

const DEFAULTS: AppSettings = {
  anthropicApiKey: '',
  defaultCropRadius: DEFAULT_CROP_RADIUS,
  defaultScreenshotDelay: DEFAULT_SCREENSHOT_DELAY_MS,
  captureTyping: true,
  captureScrolling: true,
  autoGenerateDescriptions: true,
  aiModel: DEFAULT_AI_MODEL,
  theme: 'system'
}

/**
 * Keys whose values must be encrypted at rest.
 *   - The anthropicApiKey is the only secret today.
 *   - Add new sensitive setting keys here as they are introduced.
 */
const ENCRYPTED_KEYS = new Set<keyof AppSettings>(['anthropicApiKey'])

export const settingsRepo = {
  async get(): Promise<AppSettings> {
    const db = getDb()
    const rows = db.prepare('SELECT key, value FROM settings').all() as { key: string; value: string }[]
    const map: Record<string, string> = {}
    rows.forEach((r) => {
      map[r.key] = r.value
    })

    let apiKey = map['anthropicApiKey'] ?? DEFAULTS.anthropicApiKey
    if (apiKey && looksEncrypted(apiKey)) {
      try {
        apiKey = await decryptString(apiKey)
      } catch (err) {
        logger.error('settingsRepo: failed to decrypt API key — clearing it')
        apiKey = ''
      }
    } else if (apiKey) {
      // Legacy plaintext value found from a pre-hardening release. Re-write
      // it as ciphertext on the way out.
      try {
        const cipher = await encryptString(apiKey)
        db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)').run('anthropicApiKey', cipher)
        logger.info('settingsRepo: migrated legacy plaintext API key to ciphertext')
      } catch (err) {
        logger.error(`settingsRepo: migration failed: ${String(err)}`)
      }
    }

    return {
      anthropicApiKey: apiKey,
      defaultCropRadius: map['defaultCropRadius']
        ? Number(map['defaultCropRadius'])
        : DEFAULTS.defaultCropRadius,
      defaultScreenshotDelay: map['defaultScreenshotDelay']
        ? Number(map['defaultScreenshotDelay'])
        : DEFAULTS.defaultScreenshotDelay,
      captureTyping:
        map['captureTyping'] !== undefined ? map['captureTyping'] === 'true' : DEFAULTS.captureTyping,
      captureScrolling:
        map['captureScrolling'] !== undefined
          ? map['captureScrolling'] === 'true'
          : DEFAULTS.captureScrolling,
      autoGenerateDescriptions:
        map['autoGenerateDescriptions'] !== undefined
          ? map['autoGenerateDescriptions'] === 'true'
          : DEFAULTS.autoGenerateDescriptions,
      aiModel: map['aiModel'] ?? DEFAULTS.aiModel,
      theme: (map['theme'] as AppSettings['theme']) ?? DEFAULTS.theme
    }
  },

  async set(patch: Partial<AppSettings>): Promise<void> {
    const db = getDb()
    const upsert = db.prepare('INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)')

    // Encryption is async, so we cannot do it inside a better-sqlite3
    // transaction. Encrypt first, then persist atomically.
    const prepared: Array<[string, string]> = []
    for (const [k, vRaw] of Object.entries(patch)) {
      if (vRaw === undefined) continue
      const key = k as keyof AppSettings
      const value = String(vRaw)
      if (ENCRYPTED_KEYS.has(key) && value.length > 0) {
        prepared.push([key, await encryptString(value)])
      } else {
        prepared.push([key, value])
      }
    }

    const tx = db.transaction(() => {
      for (const [k, v] of prepared) upsert.run(k, v)
    })
    tx()
  },

  /** Async variant of `getKey`, decrypts if needed. */
  async getKey(key: keyof AppSettings): Promise<string | null> {
    const row = getDb().prepare('SELECT value FROM settings WHERE key = ?').get(key) as
      | { value: string }
      | undefined
    if (!row) return null
    if (ENCRYPTED_KEYS.has(key) && looksEncrypted(row.value)) {
      try {
        return await decryptString(row.value)
      } catch {
        return null
      }
    }
    return row.value
  }
}
